version: "3.8"
services:
  # Api Gateway Service
  app-service:
    restart: always
    environment:
      # Service port
      - PORT=3000

    depends_on:
      - db-service

  # Database Service
  db-service:
    image: mongo
    restart: always
    volumes:
      - mongo-database:/data/db
volumes:
  mongo-database:
